/* Vocabulary for Carrera de Palabras.
   Everyday words for a Spanish-immersion preschooler, mixed across levels
   (greetings, food, play, people, toys, school). Each level brings a few new
   words plus a review word. `say` overrides the text that gets spoken.
   Kept as strict JSON inside `window.VOCAB = ...;` so tools/make-audio.swift can read it. */
window.VOCAB = {
  "words": {
    "hola":         { "es": "¡Hola!",          "en": "hello",        "pic": "👋" },
    "gracias":      { "es": "Gracias",         "en": "thank you",    "pic": "🙏" },
    "agua":         { "es": "el agua",         "en": "water",        "pic": "💧" },
    "leche":        { "es": "la leche",        "en": "milk",         "pic": "🥛" },
    "pelota":       { "es": "la pelota",       "en": "ball",         "pic": "⚽" },
    "libro":        { "es": "el libro",        "en": "book",         "pic": "📖" },
    "si":           { "es": "Sí",              "en": "yes",          "pic": "👍" },
    "no":           { "es": "No",              "en": "no",           "pic": "👎" },
    "nino":         { "es": "el niño",         "en": "boy",          "pic": "👦" },
    "nina":         { "es": "la niña",         "en": "girl",         "pic": "👧" },
    "galleta":      { "es": "la galleta",      "en": "cookie",       "pic": "🍪" },
    "manzana":      { "es": "la manzana",      "en": "apple",        "pic": "🍎" },
    "porfavor":     { "es": "Por favor",       "en": "please",       "pic": "🥺" },
    "juguete":      { "es": "el juguete",      "en": "toy",          "pic": "🧸" },
    "platano":      { "es": "el plátano",      "en": "banana",       "pic": "🍌" },
    "pan":          { "es": "el pan",          "en": "bread",        "pic": "🍞" },
    "bebe":         { "es": "el bebé",         "en": "baby",         "pic": "👶" },
    "globo":        { "es": "el globo",        "en": "balloon",      "pic": "🎈" },
    "buenosdias":   { "es": "¡Buenos días!",   "en": "good morning", "pic": "🌅" },
    "mama":         { "es": "mamá",            "en": "mom",          "pic": "👩" },
    "papa":         { "es": "papá",            "en": "dad",          "pic": "👨" },
    "maestra":      { "es": "la maestra",      "en": "teacher",      "pic": "👩‍🏫" },
    "jugo":         { "es": "el jugo",         "en": "juice",        "pic": "🧃" },
    "carro":        { "es": "el carro",        "en": "car",          "pic": "🚗" },
    "bano":         { "es": "el baño",         "en": "bathroom",     "pic": "🚽" },
    "lavarmanos":   { "es": "lavar las manos", "en": "wash hands",   "pic": "🧼" },
    "amigos":       { "es": "los amigos",      "en": "friends",      "pic": "🧑‍🤝‍🧑" },
    "queso":        { "es": "el queso",        "en": "cheese",       "pic": "🧀" },
    "tren":         { "es": "el tren",         "en": "train",        "pic": "🚂" },
    "bloques":      { "es": "los bloques",     "en": "blocks",       "pic": "🧱" },
    "comer":        { "es": "comer",           "en": "to eat",       "pic": "🍽️" },
    "dormir":       { "es": "dormir",          "en": "to sleep",     "pic": "😴" },
    "feliz":        { "es": "feliz",           "en": "happy",        "pic": "😀" },
    "triste":       { "es": "triste",          "en": "sad",          "pic": "😢" },
    "fresa":        { "es": "la fresa",        "en": "strawberry",   "pic": "🍓" },
    "rompecabezas": { "es": "el rompecabezas", "en": "puzzle",       "pic": "🧩" },
    "buenasnoches": { "es": "¡Buenas noches!", "en": "good night",   "pic": "🌙" },
    "jugar":        { "es": "jugar",           "en": "to play",      "pic": "🤸" },
    "correr":       { "es": "correr",          "en": "to run",       "pic": "🏃" },
    "cantar":       { "es": "cantar",          "en": "to sing",      "pic": "🎤" },
    "pintar":       { "es": "pintar",          "en": "to paint",     "pic": "🎨" },
    "crayones":     { "es": "los crayones",    "en": "crayons",      "pic": "🖍️" },
    "mochila":      { "es": "la mochila",      "en": "backpack",     "pic": "🎒" },
    "escuela":      { "es": "la escuela",      "en": "school",       "pic": "🏫" },
    "lapiz":        { "es": "el lápiz",        "en": "pencil",       "pic": "✏️" },
    "tijeras":      { "es": "las tijeras",     "en": "scissors",     "pic": "✂️" },
    "silla":        { "es": "la silla",        "en": "chair",        "pic": "🪑" },
    "zapatos":      { "es": "los zapatos",     "en": "shoes",        "pic": "👟" },
    "chaqueta":     { "es": "la chaqueta",     "en": "jacket",       "pic": "🧥" },
    "helado":       { "es": "el helado",       "en": "ice cream",    "pic": "🍦" },
    "uvas":         { "es": "las uvas",        "en": "grapes",       "pic": "🍇" },
    "zanahoria":    { "es": "la zanahoria",    "en": "carrot",       "pic": "🥕" },
    "bailar":       { "es": "bailar",          "en": "to dance",     "pic": "💃" },
    "tobogan":      { "es": "el tobogán",      "en": "slide",        "pic": "🛝" },
    "enojado":      { "es": "enojado",         "en": "angry",        "pic": "😠" },
    "cuento":       { "es": "el cuento",       "en": "story",        "pic": "📚" },
    "dinosaurio":   { "es": "el dinosaurio",   "en": "dinosaur",     "pic": "🦖" },
    "cohete":       { "es": "el cohete",       "en": "rocket",       "pic": "🚀" },
    "abrazo":       { "es": "el abrazo",       "en": "hug",          "pic": "🤗" },
    "cansado":      { "es": "cansado",         "en": "tired",        "pic": "🥱" },
    "perro":        { "es": "el perro",        "en": "dog",          "pic": "🐶" },
    "gato":         { "es": "el gato",         "en": "cat",          "pic": "🐱" }
  },
  "levels": [
    { "name": "Camino de plátanos",        "obstacle": "banana",
      "words": ["hola", "gracias", "agua", "leche", "pelota", "libro"] },
    { "name": "Charcos",        "obstacle": "puddle",
      "words": ["si", "no", "nino", "nina", "galleta", "manzana"] },
    { "name": "Conos",          "obstacle": "cone",
      "words": ["porfavor", "juguete", "platano", "pan", "bebe", "globo", "hola"] },
    { "name": "Troncos",            "obstacle": "log",
      "words": ["buenosdias", "mama", "papa", "maestra", "jugo", "carro", "pelota"] },
    { "name": "Fuego",          "obstacle": "fire",
      "words": ["bano", "lavarmanos", "amigos", "queso", "tren", "bloques", "gracias"] },
    { "name": "Picos",        "obstacle": "spikes",
      "words": ["comer", "dormir", "feliz", "triste", "fresa", "rompecabezas", "agua"] },
    { "name": "Pozos de caimanes",         "obstacle": "pit",
      "words": ["buenasnoches", "jugar", "correr", "cantar", "pintar", "crayones", "maestra"] },
    { "name": "Puente levadizo",   "obstacle": "drawbridge",
      "words": ["mochila", "escuela", "lapiz", "tijeras", "silla", "zapatos", "chaqueta", "bano"] },
    { "name": "Caimanes gigantes", "obstacle": "gatorbridge",
      "words": ["helado", "uvas", "zanahoria", "bailar", "tobogan", "enojado", "cuento", "comer"] },
    { "name": "Volcán",   "obstacle": "volcano",
      "words": ["dinosaurio", "cohete", "abrazo", "cansado", "perro", "gato", "lavarmanos", "tijeras"] }
  ],
  "phrases": {
    "es": {
      "cual":        "¿Cuál es...",
      "uy":          "¡Uy! Es este:",
      "muybien":     "¡Muy bien!",
      "excelente":   "¡Excelente!",
      "tres":        "tres",
      "dos":         "dos",
      "uno":         "uno",
      "vamos":       "¡Vamos!",
      "gas":         "¿Quieres gasolina?",
      "gaslow":      "¡Casi no tienes gasolina! ¿Quieres gasolina?",
      "lleno":       "¡Lleno!",
      "singas":      "¡Oh, no! ¡Sin gasolina!",
      "felicidades": "¡Felicidades! ¡Lo lograste!",
      "casi":        "¡Casi! ¡Otra vez!",
      "todas":       "¡Acierta todas para ganar tres estrellas!",
      "nuevonivel":  "¡Nuevo nivel!",
      "monedas":     "¡Monedas!",
      "carronuevo":  "¡Carro nuevo!",
      "tienda":      "¡La tienda de carros!"
    }
  }
};
